# Azure Storage Configuration
# Note: Sensitive information is stored in environment variables
# Required environment variables:
# - AZURE_STORAGE_ACCOUNT_NAME
# - AZURE_STORAGE_CONNECTION_STRING
# - AZURE_STORAGE_CONTAINER_NAME

# Data processing settings
data_processing:
  batch_size: 100
  max_retries: 3
  timeout_seconds: 30

# Logging configuration
logging:
  level: INFO
  file_path: "logs/fhir_processing.log" 